Import("env")

myenv = env.Copy()
myenv.Tool("qt")

myenv.Append(CPPPATH = "#")
myenv.Append(CPPPATH = myenv['QT_CPPPATH'])

myenv.StaticLibrary(target = "madmanhttpd",
  source = ["webdata/webdata.cpp", "httpd.cpp", "madmanweb.cpp"])
