#! /usr/bin/env python

import os
import os.path
import stat
import re
import sys

print "#include <cstring>"
print "#include \"designer/image_data.h\""

def print_array( filename, basename ):
  myfile = file( filename, "r" )
  data = myfile.read()
  print "static char %s[] = {" % basename
  counter = 0
  for byte in data:
    print "0x%02x," % ord(byte),
    counter = counter + 1
    if counter == 12:
      counter = 0
      print
  print "};"

class tFileDescription:
  pass

filelist = [];

for real_filename in sys.argv[1:]:
  filename = os.path.basename( real_filename )
  statbuf = os.stat( real_filename )
  if stat.S_ISREG( statbuf.st_mode ):
    c_name = filename.replace( ".", "_" )
    print_array( real_filename, c_name )
    
    description = tFileDescription()
    description.c_name = c_name
    description.filename = filename
    description.size = statbuf.st_size

    filelist.append( description )

print "const char *images::getFile( const char *name )\n{"
for description in filelist:
  print "  if ( strcmp( name, \"%s\" ) == 0 ) return %s;" % ( description.filename, description.c_name );
print "  return NULL;"
print "}"

print "int images::getFileSize( const char *name )\n{"
for description in filelist:
  print "  if ( strcmp( name, \"%s\" ) == 0 ) return %d;" % ( description.filename, description.size );
print "  return -1;"
print "}"
