import os
import glob

Import( "env" )

myenv = env.Copy()
myenv.Tool( "qt" )

myenv.Append(CPPPATH = "#")

myenv.StaticLibrary( target = "madmandesigner",
  source = [ "images/image_data.cpp", "mainwin.ui", "prefs.ui", "helpbrowser.ui", 
  "multiline_edit.ui", "about.ui", "auto_tag.ui" ] )
